# Streamlit Secrets Configuration
# This file should NOT be committed to git
# Copy this template and fill in your actual credentials

[neo4j]
uri = "bolt://220210fe.databases.neo4j.io:7687"
user = "neo4j"
password = "uefo7_cCO4KdvrpS3knrhJ39Pwn2KDrFD0NCH4SKHv8"

[mistral]
api_key = "xELPoQf6Msav4CZ7fPEAfcKnJTa4UOxn"
model = "mistral-small-latest"
